### ISSUE TITLE
沪江大学校歌

### ISSUE THREAD

**Issue by ericmetro** [luminr/xiao-ge#7]
词：作者不详，创作于1923年（来源：http://blog.sina.com.cn/s/blog_48c6bf9a0102v86i.html）
https://zh.wikipedia.org/wiki/%E6%B2%AA%E6%B1%9F%E5%A4%A7%E5%AD%A6#.E6.A0.A1.E6.AD.8C

曲：Samuel A. Ward，所作America the Beautiful
https://zh.wikipedia.org/wiki/%E7%BE%8E%E4%B8%BD%E7%9A%84%E9%98%BF%E7%BE%8E%E5%88%A9%E5%8A%A0

曲谱：
https://en.wikipedia.org/wiki/File:5_America,_the_Beautiful.png

沿革：
·沪江大学校歌（1923-1958）
·沪江高级中学校歌，台北（1958-）
·沪江小学，香港（1986-），歌词更动
http://edu.takungpao.com.hk/ksjy/gk/q/2014/1202/2845461.html

**Comment by luminr** [comment]
https://github.com/luminr/xiao-ge/wiki/%E6%B2%AA%E6%B1%9F%E5%A4%A7%E5%AD%A6%E6%A0%A1%E6%AD%8C
